# Generated by Django 5.2.14 on 2026-05-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document"), ("video", "Video")],
                        default="image",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("name_de", models.CharField(blank=True, max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name_plural": "skill categories",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("category", models.CharField(blank=True, max_length=64)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier (e.g. devicon name)", max_length=64
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "technologies",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("title_de", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("summary", models.TextField(blank=True)),
                ("summary_de", models.TextField(blank=True)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="people",
                        to="cv.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(max_length=160)),
                ("degree_de", models.CharField(blank=True, max_length=160)),
                ("institution", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_de", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educations",
                        to="cv.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_de", models.CharField(blank=True, max_length=200)),
                ("issuer", models.CharField(max_length=160)),
                ("issue_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("description_de", models.TextField(blank=True)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="cv.mediaasset",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="cv.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("xing", "Xing"),
                            ("email", "Email"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_links",
                        to="cv.person",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("name_de", models.CharField(blank=True, max_length=160)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("summary_de", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                ("description_de", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                (
                    "media",
                    models.ManyToManyField(blank=True, related_name="projects", to="cv.mediaasset"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="cv.person",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(blank=True, related_name="projects", to="cv.technology"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone"),
                            ("award", "Award"),
                            ("transition", "Transition"),
                            ("other", "Other"),
                        ],
                        default="milestone",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_de", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("description_de", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_entries",
                        to="cv.person",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "timeline entries",
                "ordering": ["-date", "order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("name_de", models.CharField(blank=True, max_length=80)),
                ("level", models.PositiveSmallIntegerField(default=3, help_text="1–5 proficiency")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="cv.skillcategory",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(blank=True, related_name="skills", to="cv.technology"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "name"), name="unique_skill_per_category"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=160)),
                ("role_de", models.CharField(blank=True, max_length=160)),
                ("company", models.CharField(max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Leave blank for current", null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("description_de", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiences",
                        to="cv.person",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="experiences", to="cv.technology"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "order"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["-start_date"], name="cv_experien_start_d_026224_idx")
                ],
            },
        ),
    ]
