# Generated by Django 5.2.14 on 2026-05-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="cv.education",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="cv.experience",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.PositiveSmallIntegerField(default=3, help_text="1-5 proficiency"),
        ),
    ]
