# Generated by Django 5.2.14 on 2026-05-20 15:05

import apps.cv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_certificate_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="zivilstand",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=apps.cv.models._generate_access_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_keys",
                        to="cv.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
