# Generated by Django 5.2.14 on 2026-05-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_person_address_person_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technology",
            name="icon",
        ),
    ]
