# Generated by Django 5.2.14 on 2026-05-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_remove_technology_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiences",
                to="cv.mediaasset",
            ),
        ),
    ]
