# Generated by Django 5.2.14 on 2026-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_experience_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="certificates", to="cv.technology"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="technologies",
            field=models.ManyToManyField(blank=True, related_name="educations", to="cv.technology"),
        ),
    ]
