# Generated by Django 5.2.14 on 2026-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_certificate_technologies_education_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="zivilstand_de",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
