# Generated by Django 5.2.14 on 2026-05-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0007_person_zivilstand_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="educations",
                to="cv.mediaasset",
            ),
        ),
    ]
