# Generated by Django 5.2.14 on 2026-06-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0008_education_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="active_funny_theme",
            field=models.CharField(
                choices=[("none", "None"), ("dog", "Dog"), ("virus", "Virus")],
                default="dog",
                help_text="Which funny theme (besides Normal) is selectable on the public site.",
                max_length=20,
            ),
        ),
    ]
