# Generated by Django 5.2.14 on 2026-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0011_readme_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="show_in_pdf",
            field=models.BooleanField(
                default=True, help_text="Include this skill in the exported CV PDF."
            ),
        ),
    ]
