# Generated by Django 5.2.14 on 2026-07-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0012_skill_show_in_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo_funny",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile picture for the active funny theme; falls back to the theme default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="people_funny",
                to="cv.mediaasset",
            ),
        ),
    ]
