# Generated by Django 5.2.14 on 2026-09-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0013_person_photo_funny"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="active_funny_theme",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("dog", "Dog"),
                    ("virus", "Virus"),
                    ("comic", "Comic"),
                ],
                default="dog",
                help_text="Which funny theme (besides Normal) is selectable on the public site.",
                max_length=20,
            ),
        ),
    ]
